name: Facebook Video Comment Bot

on:
  # Memungkinkan Anda menjalankan bot secara manual dari tab "Actions"
  workflow_dispatch:

  # Menjalankan bot secara otomatis sesuai jadwal
  schedule:
    # Contoh: Jalankan setiap 2 jam sekali
    - cron: '0 */2 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    # Memberikan izin kepada workflow untuk menulis (commit & push) ke repository
    permissions:
      contents: write

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        # Menggunakan token khusus agar bisa melakukan push
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Run the Video Bot
        run: npm run start:video
        env:
          # Mengambil cookies dan email lisensi dari GitHub Secrets
          # GEMINI_API_KEY sudah tidak diperlukan di sini
          FACEBOOK_COOKIES: ${{ secrets.FACEBOOK_COOKIES }}
          BOT_LICENSE_EMAIL: ${{ secrets.BOT_LICENSE_EMAIL }}

      - name: 5. Commit and Push Video Log File
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git pull
          
          LOG_FILE="ceklink.txt"

          if [ -s $LOG_FILE ]; then
            git add $LOG_FILE
            if ! git diff --staged --quiet; then
              git commit -m "Update video comment log ($LOG_FILE)"
              git push
            else
              echo "Tidak ada perubahan pada $LOG_FILE untuk di-commit."
            fi
          else
            echo "$LOG_FILE kosong atau tidak ada, tidak di-commit."
          fi
      
      - name: 6. Upload Debug Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots-video
          path: artifacts/
