# .github/workflows/scrape_reels.yml
name: Scrape Reels (Update Harian)

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install puppeteer
        run: npm install puppeteer

      - name: Run Scrape Reels
        run: node bot/scrape_reels.js
        env:
          FACEBOOK_COOKIES: ${{ secrets.FACEBOOK_COOKIES }}

      - name: Debug - Cek isi file
        run: cat reels_urls.txt

      - name: Commit perubahan
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reels_urls.txt
          git commit -m "💾 Update daftar Reels - $(date)" || echo "Tidak ada perubahan"
          git push origin main
